export type AeroportoBrasil = {
  sigla: string
  nome: string
  cidade: string
  uf: string
}

export const AEROPORTOS_BRASIL: AeroportoBrasil[] = [
  { sigla: 'AJU', nome: 'Santa Maria', cidade: 'Aracaju', uf: 'SE' },
  { sigla: 'ARU', nome: 'Araçatuba', cidade: 'Araçatuba', uf: 'SP' },
  { sigla: 'AUX', nome: 'Araguaína', cidade: 'Araguaína', uf: 'TO' },
  { sigla: 'BEL', nome: 'Val-de-Cans', cidade: 'Belém', uf: 'PA' },
  { sigla: 'BGX', nome: 'Comandante Gustavo Kraemer', cidade: 'Bagé', uf: 'RS' },
  { sigla: 'BNU', nome: 'Blumenau', cidade: 'Blumenau', uf: 'SC' },
  { sigla: 'BPS', nome: 'Porto Seguro', cidade: 'Porto Seguro', uf: 'BA' },
  { sigla: 'BRA', nome: 'Barreiras', cidade: 'Barreiras', uf: 'BA' },
  { sigla: 'BSB', nome: 'Presidente Juscelino Kubitschek', cidade: 'Brasília', uf: 'DF' },
  { sigla: 'BVB', nome: 'Boa Vista', cidade: 'Boa Vista', uf: 'RR' },
  { sigla: 'BVH', nome: 'Vilhena', cidade: 'Vilhena', uf: 'RO' },
  { sigla: 'CAC', nome: 'Cascavel', cidade: 'Cascavel', uf: 'PR' },
  { sigla: 'CAF', nome: 'Carauari', cidade: 'Carauari', uf: 'AM' },
  { sigla: 'CAW', nome: 'Bartolomeu Lisandro', cidade: 'Campos dos Goytacazes', uf: 'RJ' },
  { sigla: 'CCM', nome: 'Diomício Freitas', cidade: 'Criciúma', uf: 'SC' },
  { sigla: 'CFB', nome: 'Cabo Frio', cidade: 'Cabo Frio', uf: 'RJ' },
  { sigla: 'CGB', nome: 'Marechal Rondon', cidade: 'Cuiabá', uf: 'MT' },
  { sigla: 'CGH', nome: 'Congonhas', cidade: 'São Paulo', uf: 'SP' },
  { sigla: 'CGR', nome: 'Campo Grande', cidade: 'Campo Grande', uf: 'MS' },
  { sigla: 'CKS', nome: 'Carajás', cidade: 'Parauapebas', uf: 'PA' },
  { sigla: 'CLV', nome: 'Caldas Novas', cidade: 'Caldas Novas', uf: 'GO' },
  { sigla: 'CMG', nome: 'Corumbá', cidade: 'Corumbá', uf: 'MS' },
  { sigla: 'CNF', nome: 'Tancredo Neves', cidade: 'Confins', uf: 'MG' },
  { sigla: 'CPV', nome: 'Presidente João Suassuna', cidade: 'Campina Grande', uf: 'PB' },
  { sigla: 'CWB', nome: 'Afonso Pena', cidade: 'Curitiba', uf: 'PR' },
  { sigla: 'CXJ', nome: 'Hugo Cantergiani', cidade: 'Caxias do Sul', uf: 'RS' },
  { sigla: 'CZS', nome: 'Cruzeiro do Sul', cidade: 'Cruzeiro do Sul', uf: 'AC' },
  { sigla: 'DIQ', nome: 'Brigadeiro Cabral', cidade: 'Divinópolis', uf: 'MG' },
  { sigla: 'DOU', nome: 'Dourados', cidade: 'Dourados', uf: 'MS' },
  { sigla: 'ERN', nome: 'Eirunepé', cidade: 'Eirunepé', uf: 'AM' },
  { sigla: 'FEC', nome: 'Feira de Santana', cidade: 'Feira de Santana', uf: 'BA' },
  { sigla: 'FEN', nome: 'Fernando de Noronha', cidade: 'Fernando de Noronha', uf: 'PE' },
  { sigla: 'FLN', nome: 'Hercílio Luz', cidade: 'Florianópolis', uf: 'SC' },
  { sigla: 'FOR', nome: 'Pinto Martins', cidade: 'Fortaleza', uf: 'CE' },
  { sigla: 'GEL', nome: 'Santo Ângelo', cidade: 'Santo Ângelo', uf: 'RS' },
  { sigla: 'GIG', nome: 'Galeão', cidade: 'Rio de Janeiro', uf: 'RJ' },
  { sigla: 'GYN', nome: 'Santa Genoveva', cidade: 'Goiânia', uf: 'GO' },
  { sigla: 'GRU', nome: 'Guarulhos', cidade: 'Guarulhos', uf: 'SP' },
  { sigla: 'GVR', nome: 'Governador Valadares', cidade: 'Governador Valadares', uf: 'MG' },
  { sigla: 'IGU', nome: 'Foz do Iguaçu', cidade: 'Foz do Iguaçu', uf: 'PR' },
  { sigla: 'IMP', nome: 'Imperatriz', cidade: 'Imperatriz', uf: 'MA' },
  { sigla: 'IOS', nome: 'Jorge Amado', cidade: 'Ilhéus', uf: 'BA' },
  { sigla: 'IPN', nome: 'Usiminas', cidade: 'Ipatinga', uf: 'MG' },
  { sigla: 'IZA', nome: 'Zona da Mata', cidade: 'Juiz de Fora', uf: 'MG' },
  { sigla: 'JDO', nome: 'Juazeiro do Norte', cidade: 'Juazeiro do Norte', uf: 'CE' },
  { sigla: 'JDF', nome: 'Francisco Álvares de Assis', cidade: 'Juiz de Fora', uf: 'MG' },
  { sigla: 'JPA', nome: 'Presidente Castro Pinto', cidade: 'João Pessoa', uf: 'PB' },
  { sigla: 'JOI', nome: 'Joinville', cidade: 'Joinville', uf: 'SC' },
  { sigla: 'JTC', nome: 'Bauru/Arealva', cidade: 'Bauru', uf: 'SP' },
  { sigla: 'LAJ', nome: 'Lages', cidade: 'Lages', uf: 'SC' },
  { sigla: 'LDB', nome: 'Londrina', cidade: 'Londrina', uf: 'PR' },
  { sigla: 'LEC', nome: 'Lençóis', cidade: 'Lençóis', uf: 'BA' },
  { sigla: 'MAB', nome: 'Marabá', cidade: 'Marabá', uf: 'PA' },
  { sigla: 'MAO', nome: 'Eduardo Gomes', cidade: 'Manaus', uf: 'AM' },
  { sigla: 'MCP', nome: 'Macapá', cidade: 'Macapá', uf: 'AP' },
  { sigla: 'MCZ', nome: 'Zumbi dos Palmares', cidade: 'Maceió', uf: 'AL' },
  { sigla: 'MEA', nome: 'Macaé', cidade: 'Macaé', uf: 'RJ' },
  { sigla: 'MGF', nome: 'Maringá', cidade: 'Maringá', uf: 'PR' },
  { sigla: 'MII', nome: 'Marília', cidade: 'Marília', uf: 'SP' },
  { sigla: 'MOC', nome: 'Mário Ribeiro', cidade: 'Montes Claros', uf: 'MG' },
  { sigla: 'NAT', nome: 'Aluízio Alves', cidade: 'Natal', uf: 'RN' },
  { sigla: 'NVT', nome: 'Navegantes', cidade: 'Navegantes', uf: 'SC' },
  { sigla: 'OPS', nome: 'Sinop', cidade: 'Sinop', uf: 'MT' },
  { sigla: 'PAV', nome: 'Paulo Afonso', cidade: 'Paulo Afonso', uf: 'BA' },
  { sigla: 'PET', nome: 'Pelotas', cidade: 'Pelotas', uf: 'RS' },
  { sigla: 'PGZ', nome: 'Santana', cidade: 'Ponta Grossa', uf: 'PR' },
  { sigla: 'PHB', nome: 'Parnaíba', cidade: 'Parnaíba', uf: 'PI' },
  { sigla: 'PIN', nome: 'Parintins', cidade: 'Parintins', uf: 'AM' },
  { sigla: 'PLU', nome: 'Pampulha', cidade: 'Belo Horizonte', uf: 'MG' },
  { sigla: 'PMW', nome: 'Palmas', cidade: 'Palmas', uf: 'TO' },
  { sigla: 'PNZ', nome: 'Petrolina', cidade: 'Petrolina', uf: 'PE' },
  { sigla: 'POA', nome: 'Salgado Filho', cidade: 'Porto Alegre', uf: 'RS' },
  { sigla: 'PPB', nome: 'Presidente Prudente', cidade: 'Presidente Prudente', uf: 'SP' },
  { sigla: 'PSW', nome: 'Passos', cidade: 'Passos', uf: 'MG' },
  { sigla: 'PVH', nome: 'Governador Jorge Teixeira', cidade: 'Porto Velho', uf: 'RO' },
  { sigla: 'RAO', nome: 'Leite Lopes', cidade: 'Ribeirão Preto', uf: 'SP' },
  { sigla: 'RBR', nome: 'Rio Branco', cidade: 'Rio Branco', uf: 'AC' },
  { sigla: 'REC', nome: 'Guararapes', cidade: 'Recife', uf: 'PE' },
  { sigla: 'RIA', nome: 'Santa Maria', cidade: 'Santa Maria', uf: 'RS' },
  { sigla: 'ROO', nome: 'Rondonópolis', cidade: 'Rondonópolis', uf: 'MT' },
  { sigla: 'SBA', nome: 'Santa Bárbara', cidade: 'Santa Bárbara', uf: 'PA' },
  { sigla: 'SBB', nome: 'Barra do Garças', cidade: 'Barra do Garças', uf: 'MT' },
  { sigla: 'SDU', nome: 'Santos Dumont', cidade: 'Rio de Janeiro', uf: 'RJ' },
  { sigla: 'SJK', nome: 'São José dos Campos', cidade: 'São José dos Campos', uf: 'SP' },
  { sigla: 'SLZ', nome: 'Marechal Cunha Machado', cidade: 'São Luís', uf: 'MA' },
  { sigla: 'STM', nome: 'Santarém', cidade: 'Santarém', uf: 'PA' },
  { sigla: 'TBT', nome: 'Tabatinga', cidade: 'Tabatinga', uf: 'AM' },
  { sigla: 'TFF', nome: 'Tefé', cidade: 'Tefé', uf: 'AM' },
  { sigla: 'THE', nome: 'Senador Petrônio Portella', cidade: 'Teresina', uf: 'PI' },
  { sigla: 'TOW', nome: 'Toledo', cidade: 'Toledo', uf: 'PR' },
  { sigla: 'UBA', nome: 'Mário de Almeida Franco', cidade: 'Uberaba', uf: 'MG' },
  { sigla: 'UDI', nome: 'Uberlândia', cidade: 'Uberlândia', uf: 'MG' },
  { sigla: 'UNA', nome: 'Una-Comandatuba', cidade: 'Una', uf: 'BA' },
  { sigla: 'URG', nome: 'Rubem Berta', cidade: 'Uruguaiana', uf: 'RS' },
  { sigla: 'VAG', nome: 'Major Brigadeiro Trompowsky', cidade: 'Varginha', uf: 'MG' },
  { sigla: 'VCP', nome: 'Viracopos', cidade: 'Campinas', uf: 'SP' },
  { sigla: 'VDC', nome: 'Vitória da Conquista', cidade: 'Vitória da Conquista', uf: 'BA' },
  { sigla: 'VIX', nome: 'Eurico de Aguiar Salles', cidade: 'Vitória', uf: 'ES' },
  { sigla: 'XAP', nome: 'Serafim Enoss Bertaso', cidade: 'Chapecó', uf: 'SC' },
]
